### ISSUE TITLE
LICENSE.md file?

### ISSUE THREAD

**Issue by th174** [Lucytheanimefan/anime-server#1]
How is the content here licensed? This repository is missing a LICENSE.md file.

I'd like to be able to contribute and/or use the code contained here, and I would like to know if that's okay with the repo owner. 

Github has an [article providing assistance](https://help.github.com/articles/adding-a-license-to-a-repository/) on adding a license to a repository.

**Comment by Lucytheanimefan** [comment]
Contribute/use away.
